"""is_admin added

Revision ID: 4383862ca079
Revises: 966cb970afc7
Create Date: 2025-01-21 04:29:19.056455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4383862ca079'
down_revision = '966cb970afc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
